jobs:
- job: 'Prebuild'
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
    - script: ./CI/generate-docs.sh
      displayName: 'Generate docs'

# - job: 'Build_Windows'
#   dependsOn: Prebuild
#   pool:
#     vmImage: 'windows-2019'
#   steps:
#     - script: false

- job: 'Build_Linux'
  dependsOn: Prebuild
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
    - checkout: self
      submodules: true

    - script: ./CI/install-dependencies-xenial.sh
      displayName: 'Install dependencies'

    - script: ./CI/build-xenial.sh
      displayName: 'Build obs-websocket'

    - script: ./CI/package-xenial.sh
      displayName: 'Package obs-websocket'

    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: './package'
        artifactName: 'deb_build'

- job: 'Build_macOS'
  dependsOn: Prebuild
  pool:
    vmImage: 'macos-10.13'
  steps:
    - checkout: self
      submodules: true

    - script: ./CI/install-dependencies-macos.sh
      displayName: 'Install dependencies'

    - script: ./CI/install-build-obs-macos.sh
      displayName: 'Build OBS'

    - script: ./CI/build-macos.sh
      displayName: 'Build obs-websocket'

    - script: ./CI/package-macos.sh
      displayName: 'Package obs-websocket'

    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: './release'
        artifactName: 'macos_build'
